"""
🍷 Wine Quality Predictor — Streamlit App
==========================================
Requires (generated by model_training.py):
    best_wine_model.pkl
    wine_scaler.pkl
    feature_names.pkl
    model_meta.pkl

Run:  streamlit run app.py
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib, os

# ─────────────────────────────────────────────────────────────────────────────
# Page config
# ─────────────────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="🍷 Wine Quality Predictor",
    page_icon="🍷",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ─────────────────────────────────────────────────────────────────────────────
# CSS
# ─────────────────────────────────────────────────────────────────────────────
st.markdown("""
<style>
    .main-title {
        font-size: 2.6rem; font-weight: 700; color: #7c0a02;
        text-align: center; margin-bottom: 4px;
    }
    .sub-title {
        font-size: 1.05rem; color: #555; text-align: center;
        margin-bottom: 28px;
    }
    .metric-card {
        background: #fff8f8; border: 1.5px solid #e8b4b8;
        border-radius: 12px; padding: 16px 22px; text-align: center;
    }
    .metric-card h3 { margin: 0; color: #7c0a02; font-size: 1.5rem; }
    .metric-card p  { margin: 4px 0 0; color: #666; font-size: 0.9rem; }
    .quality-badge {
        font-size: 3.2rem; font-weight: 800; text-align: center;
        margin: 10px 0;
    }
    .stSlider > div > div { accent-color: #7c0a02; }
    .sidebar-header {
        font-size: 1.1rem; font-weight: 700; color: #7c0a02;
        margin-bottom: 8px;
    }
</style>
""", unsafe_allow_html=True)


# ─────────────────────────────────────────────────────────────────────────────
# Load artifacts
# ─────────────────────────────────────────────────────────────────────────────
@st.cache_resource
def load_artifacts():
    missing = [f for f in ["best_wine_model.pkl", "wine_scaler.pkl",
                            "feature_names.pkl", "model_meta.pkl"]
               if not os.path.exists(f)]
    if missing:
        return None, None, None, None
    model    = joblib.load("best_wine_model.pkl")
    scaler   = joblib.load("wine_scaler.pkl")
    features = joblib.load("feature_names.pkl")
    meta     = joblib.load("model_meta.pkl")
    return model, scaler, features, meta

@st.cache_data
def load_data():
    if not os.path.exists("winequality-red.csv"):
        return None
    df = pd.read_csv("winequality-red.csv")
    df["acidity_ratio"]   = df["fixed acidity"] / (df["volatile acidity"] + 1e-9)
    df["so2_ratio"]       = df["free sulfur dioxide"] / (df["total sulfur dioxide"] + 1e-9)
    df["alcohol_density"] = df["alcohol"] / df["density"]
    return df

model, scaler, feature_names, meta = load_artifacts()
df = load_data()


# ─────────────────────────────────────────────────────────────────────────────
# Guard — model not trained yet
# ─────────────────────────────────────────────────────────────────────────────
if model is None:
    st.error("⚠️  Model files not found. Please run **model_training.py** first.")
    st.code("python model_training.py", language="bash")
    st.stop()

if df is None:
    st.error("⚠️  Dataset **winequality-red.csv** not found in this folder.")
    st.stop()


# ─────────────────────────────────────────────────────────────────────────────
# Sidebar — input sliders
# ─────────────────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown('<p class="sidebar-header">🍷 Enter Wine Chemical Properties</p>',
                unsafe_allow_html=True)
    st.markdown("---")

    # Raw features only — engineered ones are derived automatically
    raw_cols = [
        "fixed acidity", "volatile acidity", "citric acid",
        "residual sugar", "chlorides",
        "free sulfur dioxide", "total sulfur dioxide",
        "density", "pH", "sulphates", "alcohol"
    ]

    user_vals = {}
    for col in raw_cols:
        label = col.replace(" ", " ").title()
        lo  = float(df[col].min())
        hi  = float(df[col].max())
        mid = float(df[col].mean())
        user_vals[col] = st.slider(label, lo, hi, mid,
                                   step=round((hi - lo) / 100, 4))

    st.markdown("---")
    predict_btn = st.button("🔮 Predict Quality", use_container_width=True)


# ─────────────────────────────────────────────────────────────────────────────
# Main — header
# ─────────────────────────────────────────────────────────────────────────────
st.markdown('<p class="main-title">🍷 Red Wine Quality Predictor</p>',
            unsafe_allow_html=True)
st.markdown('<p class="sub-title">Powered by Machine Learning — adjust sliders and click Predict</p>',
            unsafe_allow_html=True)

# ─── Model info bar ───────────────────────────────────────────────────────────
c1, c2, c3, c4 = st.columns(4)
with c1:
    st.markdown(f"""<div class="metric-card">
        <h3>{meta["label"]}</h3><p>Best Model</p></div>""",
        unsafe_allow_html=True)
with c2:
    st.markdown(f"""<div class="metric-card">
        <h3>{meta["R2"]:.3f}</h3><p>R² Score</p></div>""",
        unsafe_allow_html=True)
with c3:
    st.markdown(f"""<div class="metric-card">
        <h3>{meta["MAE"]:.3f}</h3><p>Mean Absolute Error</p></div>""",
        unsafe_allow_html=True)
with c4:
    st.markdown(f"""<div class="metric-card">
        <h3>{meta["RMSE"]:.3f}</h3><p>RMSE</p></div>""",
        unsafe_allow_html=True)

st.markdown("---")

# ─────────────────────────────────────────────────────────────────────────────
# Prediction
# ─────────────────────────────────────────────────────────────────────────────
def build_input_df(user_vals):
    row = dict(user_vals)
    # Derived features (same as training)
    row["acidity_ratio"]   = row["fixed acidity"]  / (row["volatile acidity"] + 1e-9)
    row["so2_ratio"]       = row["free sulfur dioxide"] / (row["total sulfur dioxide"] + 1e-9)
    row["alcohol_density"] = row["alcohol"] / row["density"]
    return pd.DataFrame([row])[feature_names]

def quality_emoji(score):
    if   score >= 7.5: return "🏆 Excellent"
    elif score >= 6.5: return "😊 Good"
    elif score >= 5.5: return "🙂 Average"
    else:              return "😕 Below Average"

def quality_color(score):
    if   score >= 7.5: return "#1a7a1a"
    elif score >= 6.5: return "#2171b5"
    elif score >= 5.5: return "#d95f02"
    else:              return "#a50026"

# Compute prediction immediately (live) and on button press
input_df   = build_input_df(user_vals)
input_sc   = scaler.transform(input_df)
pred_score = round(float(model.predict(input_sc)[0]), 2)

left_col, right_col = st.columns([1, 1])

with left_col:
    st.subheader("🔢 Your Input Features")
    disp = pd.DataFrame({"Feature": list(user_vals.keys()),
                         "Value":   list(user_vals.values())})
    st.dataframe(disp.set_index("Feature"), use_container_width=True)

with right_col:
    st.subheader("🎯 Predicted Wine Quality")
    color  = quality_color(pred_score)
    label  = quality_emoji(pred_score)
    st.markdown(f"""
        <div style="border:2px solid {color}; border-radius:14px;
                    padding:24px; text-align:center; background:#fafafa;">
            <div class="quality-badge" style="color:{color};">{pred_score}</div>
            <div style="font-size:1.4rem; color:{color}; font-weight:600;">
                {label}
            </div>
            <div style="color:#888; margin-top:8px;">
                Scale: 3 (poor) — 8 (excellent)
            </div>
        </div>
    """, unsafe_allow_html=True)

    st.markdown("&nbsp;")

    # ── Gauge-style bar ───────────────────────────────────────────────────────
    fig_g, ax_g = plt.subplots(figsize=(5, 1.2))
    bar_colors = ["#d73027", "#f46d43", "#fee090", "#74add1", "#313695"]
    for i, (lo, hi, c) in enumerate(
            [(3, 4.2, "#d73027"), (4.2, 5.4, "#f46d43"),
             (5.4, 6.4, "#fee090"), (6.4, 7.2, "#74add1"),
             (7.2, 9,   "#313695")]):
        ax_g.barh(0, hi - lo, left=lo, color=c, height=0.5, alpha=0.85)
    ax_g.axvline(pred_score, color="black", linewidth=3, linestyle="--")
    ax_g.text(pred_score, 0.35, f"{""}",
              ha="center", va="bottom", fontsize=10, fontweight="bold")
    ax_g.set_xlim(3, 9)
    ax_g.set_yticks([])
    ax_g.set_xlabel("Quality Score")
    ax_g.set_title("Quality Scale", fontsize=10)
    st.pyplot(fig_g, use_container_width=True)

st.markdown("---")

# ─────────────────────────────────────────────────────────────────────────────
# Tabs — EDA, Model Perf, Dataset
# ─────────────────────────────────────────────────────────────────────────────
tab1, tab2, tab3 = st.tabs(["📊 EDA & Correlations",
                             "📈 Model Performance",
                             "🗃️ Dataset Preview"])

with tab1:
    st.subheader("Feature Correlation Heatmap")
    fig_h, ax_h = plt.subplots(figsize=(11, 7))
    mask = np.triu(np.ones_like(df.corr(), dtype=bool))
    sns.heatmap(df.corr(), mask=mask, annot=True, fmt=".2f",
                cmap="coolwarm", linewidths=0.4,
                annot_kws={"size": 8}, ax=ax_h)
    ax_h.set_title("Correlation Matrix — Red Wine Features", fontsize=13)
    st.pyplot(fig_h, use_container_width=True)

    col_a, col_b = st.columns(2)
    with col_a:
        st.subheader("Quality Distribution")
        fig_q, ax_q = plt.subplots(figsize=(5, 3.5))
        df["quality"].value_counts().sort_index().plot(
            kind="bar", color="#7c0a02", edgecolor="black", alpha=0.8, ax=ax_q)
        ax_q.set_xlabel("Quality Score")
        ax_q.set_ylabel("Count")
        ax_q.set_title("Wine Count per Quality Level")
        plt.xticks(rotation=0)
        st.pyplot(fig_q, use_container_width=True)

    with col_b:
        st.subheader("Alcohol vs Quality")
        fig_a, ax_a = plt.subplots(figsize=(5, 3.5))
        sns.boxplot(x="quality", y="alcohol", data=df,
                    palette="viridis", ax=ax_a)
        ax_a.set_title("Alcohol Content vs Wine Quality")
        st.pyplot(fig_a, use_container_width=True)

with tab2:
    st.subheader("Model Performance Comparison")
    if os.path.exists("model_comparison.png"):
        st.image("model_comparison.png", use_column_width=True)
    else:
        st.info("Run **model_training.py** to generate the comparison chart.")

    st.subheader("Residual Plot — Best Model on Test Set")
    from sklearn.model_selection import train_test_split as tts
    df2 = df.drop_duplicates().copy()
    X2  = df2.drop("quality", axis=1)
    y2  = df2["quality"]
    _, Xt, _, yt = tts(X2, y2, test_size=0.2, random_state=42)
    Xt_sc  = scaler.transform(Xt[feature_names])
    yt_hat = model.predict(Xt_sc)
    resid  = yt - yt_hat

    fig_r, axes_r = plt.subplots(1, 2, figsize=(12, 4))
    axes_r[0].scatter(yt_hat, resid, alpha=0.45,
                      color="#7c0a02", edgecolors="k", s=25)
    axes_r[0].axhline(0, color="black", linestyle="--")
    axes_r[0].set_xlabel("Predicted Quality")
    axes_r[0].set_ylabel("Residual")
    axes_r[0].set_title("Residuals vs Predicted")

    axes_r[1].hist(resid, bins=22, color="#7c0a02",
                   edgecolor="black", alpha=0.75)
    axes_r[1].set_xlabel("Residual")
    axes_r[1].set_ylabel("Count")
    axes_r[1].set_title("Residual Distribution")

    plt.tight_layout()
    st.pyplot(fig_r, use_container_width=True)

with tab3:
    st.subheader("Dataset Preview (first 100 rows)")
    st.dataframe(df.head(100), use_container_width=True)
    st.write(f"**Total rows:** {len(df)}  |  "
             f"**Features:** {df.shape[1] - 1}  |  "
             f"**Target:** quality (3–8)")
    st.download_button("⬇️ Download full CSV",
                       data=df.to_csv(index=False),
                       file_name="winequality-red-processed.csv",
                       mime="text/csv")
